language: python
    
python: "3.6"
    
# don't clone more than necessary
git:
  depth: 1
    
# Install dependencies
install:
  - pip install -r requirements.txt
    
# script to run tests. Script can have many commands, one per line.
before_script:
  - cp .env.example .env
  - python manage.py makemigrations
  - python manage.py migrate
script: 
  - python manage.py shell
  - python manage.py test polls
env:
  - TRAVIS_SECURE_ENV_VARS=true